package Principal;

/**
 * Es un JFrame donde está la pantalla que habrá inicialmente en el proyecto.
 *
 * @author Andrés Quintero
 * @author Juan Esteban Gutiérrez
 */
public class PantallaInicio extends javax.swing.JFrame {

    /**
     * Aquí se encuentran las características que tiene la pantalla inicial. Se
     * centra la ventana.
     */
    public PantallaInicio() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAcercaDe = new java.awt.Button();
        botonEmpezar = new java.awt.Button();
        botonSalir = new java.awt.Button();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAcercaDe.setBackground(new java.awt.Color(51, 51, 255));
        botonAcercaDe.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonAcercaDe.setForeground(new java.awt.Color(255, 255, 255));
        botonAcercaDe.setLabel("Acerca de Maze App");
        botonAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcercaDeActionPerformed(evt);
            }
        });
        getContentPane().add(botonAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 60));

        botonEmpezar.setBackground(new java.awt.Color(51, 51, 255));
        botonEmpezar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonEmpezar.setForeground(new java.awt.Color(255, 255, 255));
        botonEmpezar.setLabel("¡Empezar!");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 180, 60));

        botonSalir.setBackground(new java.awt.Color(204, 0, 0));
        botonSalir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setLabel("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 100, 40));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoInicio.jpg"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El botón traslada al usuario a la ventana donde se encuentra información
     * de la aplicación.
     *
     * @param evt Se genera el evento asignado.
     */
    private void botonAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcercaDeActionPerformed
        PantallaAcercaDe pantalla = new PantallaAcercaDe();
        pantalla.setVisible(true);
    }//GEN-LAST:event_botonAcercaDeActionPerformed

    /**
     * El botón traslada al usuario a la ventana donde se encuentra el
     * laberinto.
     *
     * @param evt Se genera el evento asignado.
     */
    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        new Ventana().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonEmpezarActionPerformed

    /**
     * El botón hace que se la aplicación termine su ejecución.
     *
     * @param evt Se genera el evento asignado.
     */
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botonAcercaDe;
    private java.awt.Button botonEmpezar;
    private java.awt.Button botonSalir;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
}
