package Principal;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * JFrame Form ventana, es donde está la ventana principal del juego, donde
 * se encuentra el panel del laberinto y los botones para crear laberinto y
 * solucionarlo.
 *
 * @author Andrés Quintero
 * @author Juan Esteban Gutiérrez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Aquí se encuentran las características que tiene la ventana principal
     */
    public Ventana() {
        this.setLocation(300, 50);
        this.getContentPane().setBackground(new Color(0, 102, 255));
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLaberinto = new PanelLaberinto();
        crearLaberinto = new javax.swing.JButton();
        solucionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        panelLaberinto.setBackground(new java.awt.Color(255, 255, 0));
        panelLaberinto.setForeground(new java.awt.Color(255, 255, 255));
        panelLaberinto.setPreferredSize(new java.awt.Dimension(530, 530));

        javax.swing.GroupLayout panelLaberintoLayout = new javax.swing.GroupLayout(panelLaberinto);
        panelLaberinto.setLayout(panelLaberintoLayout);
        panelLaberintoLayout.setHorizontalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        panelLaberintoLayout.setVerticalGroup(
            panelLaberintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        crearLaberinto.setBackground(new java.awt.Color(0, 0, 0));
        crearLaberinto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crearLaberinto.setForeground(new java.awt.Color(255, 255, 255));
        crearLaberinto.setText("Crear laberinto");
        crearLaberinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLaberintoActionPerformed(evt);
            }
        });

        solucionar.setBackground(new java.awt.Color(0, 0, 0));
        solucionar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        solucionar.setForeground(new java.awt.Color(255, 255, 255));
        solucionar.setText("Solucionar");
        solucionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solucionarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número de renglones");

        spinner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 75, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(crearLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                .addComponent(panelLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(crearLaberinto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(solucionar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addComponent(panelLaberinto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        solucionar.getAccessibleContext().setAccessibleName("Solucionar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * El método le da funcionalidad al botón Crear laberinto.
     *
     * @param evt Genera el evento asociado.
     */
    private void crearLaberintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLaberintoActionPerformed
        this.panelLaberinto.setSolucionar(false);
        this.panelLaberinto.setLaberinto((int) this.spinner.getValue());
        this.panelLaberinto.getLaberinto().crearLaberinto();
        this.panelLaberinto.repaint();
    }//GEN-LAST:event_crearLaberintoActionPerformed

    /**
     * El método le da funcionalidad al botón Solucionar laberinto, dando una
     * advertencia si el usuario quiere solucionar el laberinto sin haberlo
     * generado.
     *
     * @param evt Genera el evento asociado.
     */
    private void solucionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucionarActionPerformed
        if (this.panelLaberinto.getLaberinto().getArbol().getNodoHojaFin() == null) {
            JOptionPane.showMessageDialog(null, "Genere primero un laberinto", "¡ALERTA!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        panelLaberinto.setSolucionar(true);

        this.panelLaberinto.repaint();
    }//GEN-LAST:event_solucionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PantallaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearLaberinto;
    private javax.swing.JLabel jLabel1;
    private PanelLaberinto panelLaberinto;
    private javax.swing.JButton solucionar;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
